### ISSUE TITLE
Problems encountered when adding Frontier (polkadot-v0.9.17)

### ISSUE THREAD

**Issue by 99Kies** [flipchan/frontier-pallet-upstream#2]
<img width="1501" alt="image" src="https://user-images.githubusercontent.com/45918704/160274941-58e4778b-b12d-466a-a90e-347659cb76a7.png">

**Comment by flipchan** [comment]
@99Kies this is currently a work in progress, find a better version here: https://github.com/edgeware-network/frontier branch: erup-5-latest

**Comment by 99Kies** [comment]
@flipchan but it's not support `polkadot-v0.9.17`.
![image](https://user-images.githubusercontent.com/45918704/160285609-3c5f2c6d-bfd0-4e4e-889e-d330f5b7aa46.png)
